# Generated by Django 4.2.6 on 2024-03-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_farmer",
            field=models.BooleanField(verbose_name=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_government",
            field=models.BooleanField(verbose_name=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_ngo",
            field=models.BooleanField(verbose_name=False),
        ),
    ]
