# Generated by Django 4.2.6 on 2024-03-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_is_farmer_alter_user_is_government_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_farmer",
            field=models.BooleanField(null=True, verbose_name=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_government",
            field=models.BooleanField(null=True, verbose_name=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_ngo",
            field=models.BooleanField(null=True, verbose_name=False),
        ),
    ]
