# Generated by Django 4.2.6 on 2024-03-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_is_farmer_alter_user_is_government_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="phone",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="government",
            name="phone",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="company_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="phone",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
