# Generated by Django 4.2.6 on 2024-03-05 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_farmer_phone_alter_government_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="government",
            name="user",
        ),
        migrations.RemoveField(
            model_name="ngo",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_farmer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_government",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_ngo",
        ),
        migrations.DeleteModel(
            name="Farmer",
        ),
        migrations.DeleteModel(
            name="Government",
        ),
        migrations.DeleteModel(
            name="Ngo",
        ),
    ]
